-- AlterEnum: tambah tipe notifikasi untuk perubahan data sensitif
-- (flip status rumah ke KOSONG, koreksi nominal tagihan) yang dikirim ke RW.
ALTER TABLE `tb_Notifikasi` MODIFY COLUMN `tipe` ENUM('TAGIHAN_BARU', 'PEMBAYARAN_DIKONFIRMASI', 'PEMBAYARAN_DITOLAK', 'PEMBAYARAN_MASUK', 'PENGADUAN_BARU', 'PENGADUAN_DITANGGAPI', 'PENGADUAN_DITERUSKAN', 'PENDAFTARAN_BARU', 'PENGUMUMAN_BARU', 'KEGIATAN_BARU', 'SETORAN_MASUK', 'SETORAN_DIKONFIRMASI', 'SETORAN_DITOLAK', 'PENGAJUAN_MASUK', 'PENGAJUAN_DISETUJUI', 'PENGAJUAN_DITOLAK', 'PERUBAHAN_DATA') NOT NULL;
